osx_image: xcode11.4
language: objective-c
script:
    - |
      xcodebuild test \
      -project Rexxar.xcodeproj \
      -scheme RexxarTests \
      -sdk iphonesimulator \
      -destination 'platform=iOS Simulator,name=iPhone 8,OS=13.3' \
      ONLY_ACTIVE_ARCH=NO
